# Changes here will be overwritten by Copier
_commit: 3aa4aef
_src_path: gh:browniebroke/pypackage-template
add_me_as_contributor: false
copyright_year: "2023"
documentation: true
email: felix@kaechele.ca
full_name: Felix Kaechele
github_username: kaechele
initial_commit: false
open_source_license: MIT
package_name: bonaparte
project_name: Bonaparte
project_short_description: Library to control Napoleon eFIRE enabled fireplaces
project_slug: bonaparte
run_poetry_install: false
setup_github: false
setup_pre_commit: false
