[tool.poetry]
name = "bonaparte"
version = "0.1.0"
description = "Library to control Napoleon eFIRE enabled fireplaces"
authors = ["Felix Kaechele <felix@kaechele.ca>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/kaechele/bonaparte"
documentation = "https://bonaparte.readthedocs.io"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Topic :: Home Automation",
    "Topic :: Software Development :: Libraries",
]
packages = [
    { include = "bonaparte", from = "src" },
]

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/kaechele/bonaparte/issues"
"Changelog" = "https://github.com/kaechele/bonaparte/blob/main/CHANGELOG.md"

[tool.poetry.dependencies]
python = "^3.10"
bleak = "^0.19.5"
bleak-retry-connector = "^2.13.1"
async-timeout = "^4.0.2"
aenum = "^3.1.11"

[tool.poetry.group.dev.dependencies]
pytest = "^7.0"
pytest-cov = "^3.0"
black = "^23.1.0"
pylint = "^2.16.2"

[tool.poetry.group.docs]
optional = true

[tool.poetry.group.docs.dependencies]
myst-parser = ">=0.16"
sphinx = ">=4.0"
sphinx-rtd-theme = ">=1.0"

[tool.semantic_release]
branch = "main"
version_toml = "pyproject.toml:tool.poetry.version"
version_variable = "src/bonaparte/__init__.py:__version__"
build_command = "pip install poetry && poetry build"

[tool.pytest.ini_options]
addopts = "-v -Wdefault --cov=bonaparte --cov-report=term-missing:skip-covered"
pythonpath = ["src"]

[tool.black]
target-version = ["py310", "py311"]

[tool.coverage.run]
branch = true

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "@overload",
    "if TYPE_CHECKING",
    "raise NotImplementedError",
    'if __name__ == "__main__":',
]

[tool.isort]
profile = "black"
known_first_party = ["bonaparte", "tests"]

[tool.mypy]
python_version = "3.10"
check_untyped_defs = true
disallow_any_generics = true
disallow_incomplete_defs = true
disallow_untyped_defs = true
mypy_path = "src/"
no_implicit_optional = true
show_error_codes = true
warn_unreachable = true
warn_unused_ignores = true
exclude = [
    'docs/.*',
    'setup.py',
]

[[tool.mypy.overrides]]
module = "tests.*"
allow_untyped_defs = true

[[tool.mypy.overrides]]
module = "docs.*"
ignore_errors = true

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
